# Generated by Django 4.2.7 on 2025-09-09 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='employee_name',
            field=models.CharField(default='______', max_length=50),
        ),
    ]
