# Generated by Django 4.2.7 on 2025-09-09 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_faculty_employee_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='user',
        ),
    ]
