# Generated by Django 4.2.7 on 2025-09-10 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_remove_faculty_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='subjects',
        ),
        migrations.AlterField(
            model_name='faculty',
            name='employee_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
